### ISSUE TITLE
Connect failed, create socket failed.

### ISSUE THREAD

**Issue by Hadatko** [awslabs/aws-c-io#304] opened 2020-07-25 12:37 UTC
Hi,
i am trying to connect to aws iot cloud using aws-iot-device-sdk-python-v2. Everytime i am starting app, or when reconnecting i am getting these errors finished by Connected message and application is working well. But i am curios why these errors happening? Looks like they are related to this repository. Demo code example: https://github.com/aws/aws-iot-device-sdk-python-v2/issues/90

[ERROR] [2020-07-25T12:30:01Z] [00007f5d7b0ac700] [socket] - id=0x7f5d6c004e90 fd=6: connect failed with error code 101.
[INFO ] [2020-07-25T12:30:01Z] [00007f5d7b0ac700] [dns] - id=0x1004a40: recording failure for record 2600:1f00:6000::385:ab7e for a1tuyp21t3nvof-ats.iot.us-east-2.amazonaws.com, moving to bad list
[ERROR] [2020-07-25T12:30:01Z] [00007f5d7b0ac700] [channel-bootstrap] - id=0x1032890: failed to create socket with error 1049
[INFO ] [2020-07-25T12:30:01Z] [00007f5d7b0ac700] [socket] - id=0x7f5d6c004e90 fd=6: connection success
[aws] Connected!

**Comment by JonathanHenson** [comment] 2020-07-25 18:25
It looks like the ipv6 connect is failing (immediately because it’s an invalid route, hence the reuse of the same fd), and it’s connecting on the ipv4 address. This is expected behavior.

**Comment by Hadatko** [comment] 2020-07-26 07:27
Ok. It is weird to have errors as expected behavior. Are you able to find out if device has ipv6 address before trying to use that?

**Comment by JonathanHenson** [comment] 2020-07-26 18:53
Well, we can change the log level, if that’s what’s concerning you. Since devices network configurations change (for example if a vpn tunnel is being used or if you change networks etc...) we’d rather not keep State that’s unnecessary about the network conditions: that’s just more opportunities for some rather nasty bugs.

**Comment by Hadatko** [comment] 2020-07-26 20:04
It is up to you. I would prefer to get rid of errors in working application (that is confusing for me at least). If i would write something like that in python if i understand this use case correctly it would looks like:
```
try:
   socketIPV6()
except:
   print("INFO: Could not connect with ipv6. Trying ipv4")
   try:
       socketIPV4()
   except:
       print("ERROR: Could not connected to AWS even with ipv4")
       return
```

**Comment by TingDaoK** [comment] 2023-08-24 17:38
Close the issue as we downgraded the log level for socket connection. https://github.com/awslabs/aws-c-io/pull/594

**Closed by TingDaoK** 2023-08-24 17:38 UTC
Labels: feature-request, p3, needs-review
